AWSTemplateFormatVersion: 2010-09-09

Description: AWS CloudFormation Template for GitHub Actions OIDC

Parameters:
  GitHubOrg:
    Type: String
  RepositoryName:
    Type: String

Resources:
  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated: !Ref GithubOIDCProvider
            Condition:
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub repo:${GitHubOrg}/${RepositoryName}:*
              ForAllValues:StringEquals:
                token.actions.githubusercontent.com:iss: "https://token.actions.githubusercontent.com"
                token.actions.githubusercontent.com:aud: "sts.amazonaws.com"
      RoleName: !Sub gha_oidc_role_${RepositoryName}

  GithubOIDCProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1

Outputs:
  Role:
    Value: !GetAtt Role.Arn
